language: ruby

rvm:
 - 2.1
 - 2.2
 - 2.3
 - 2.4.0
 - jruby-9.1.6.0
 - ruby-head

gemfile:
 - gemfiles/Gemfile

matrix:
  allow_failures:
    - rvm: ruby-head

before_install:
  - "gem update --system"
  - "gem update bundler"
